apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: juliafmorgado/challenge-4-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: db
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: challenge4
