version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge3
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount SQL initialization script

  app:
    build: ./app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - db

  dashboard:
    build: ./dashboard
    command: npm start
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  postgres-data:
